envsubst '${OIDCResponseType}' | \
envsubst '${OIDCCryptoPassphrase}' | \
envsubst '${OIDCCookieDomain}' | \
envsubst '${OIDCSSLValidateServer}' | \
envsubst '${OIDCProviderMetadataURL}' | \
envsubst '${OIDCPassClaimsAs}' | \
envsubst '${LimitRequestFieldSize}' | \
envsubst '${ServerName}' | \
envsubst '${LogFormat}' | \
envsubst '${CustomLog}' | \
envsubst '${ProxyPass}' | \
envsubst '${OIDCRedirectURI}' | \
envsubst '${OIDCClientID}' | \
envsubst '${OIDCClientSecret}' | \
envsubst '${OIDCSessionInactivityTimeout}' | \
envsubst '${OIDCSessionMaxDuration}' | \
envsubst '${OIDCSessionType}' | \
envsubst '${OIDCSessionCookieChunkSize}' | \
envsubst '${OIDCPassRefreshToken}' | \
envsubst '${OIDCCookie}' | \
envsubst '${httpd_debugdump}' | \
envsubst '${ServerNameForUnknownHostAccess}' | \
cat 
